name: unipool
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  cloud_firestore: ^6.3.0
  firebase_auth: ^6.5.0
  firebase_core: ^4.7.0
  cloud_functions: ^6.3.0
  firebase_messaging: ^16.2.0
  firebase_storage: ^13.3.0
  cached_network_image: ^3.4.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.14.0
  intl: ^0.20.2
  image_picker: ^1.2.2
  provider: ^6.1.5
  uuid: ^4.5.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
