// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK7z-cFcxFb7RNkGWFtnxcVHMLAEAc25A',
    appId: '1:150858198157:web:71514619cdf4e20d8dc6c4',
    messagingSenderId: '150858198157',
    projectId: 'unipool-24613',
    authDomain: 'unipool-24613.firebaseapp.com',
    storageBucket: 'unipool-24613.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCODwV_35JXOreC7rTg9L9ZWwaFWpDHoes',
    appId: '1:150858198157:android:f9c9d61a9293ee238dc6c4',
    messagingSenderId: '150858198157',
    projectId: 'unipool-24613',
    storageBucket: 'unipool-24613.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8BepS39IYUToyfYCR5egHqGEitCp4H7E',
    appId: '1:150858198157:ios:4c8d1bcc2b7105f48dc6c4',
    messagingSenderId: '150858198157',
    projectId: 'unipool-24613',
    storageBucket: 'unipool-24613.firebasestorage.app',
    iosBundleId: 'com.example.unipool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8BepS39IYUToyfYCR5egHqGEitCp4H7E',
    appId: '1:150858198157:ios:4c8d1bcc2b7105f48dc6c4',
    messagingSenderId: '150858198157',
    projectId: 'unipool-24613',
    storageBucket: 'unipool-24613.firebasestorage.app',
    iosBundleId: 'com.example.unipool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK7z-cFcxFb7RNkGWFtnxcVHMLAEAc25A',
    appId: '1:150858198157:web:722a065c926931958dc6c4',
    messagingSenderId: '150858198157',
    projectId: 'unipool-24613',
    authDomain: 'unipool-24613.firebaseapp.com',
    storageBucket: 'unipool-24613.firebasestorage.app',
  );
}
