/// Complete list of universities and colleges in Malaysia.
/// Includes public universities (IPTA), private universities (IPTS),
/// polytechnics, and community colleges.
const List<String> malaysianUniversities = [
  // ── Public Universities (IPTA) ──────────────────────────────────────────
  'Universiti Malaya (UM)',
  'Universiti Sains Malaysia (USM)',
  'Universiti Kebangsaan Malaysia (UKM)',
  'Universiti Putra Malaysia (UPM)',
  'Universiti Teknologi Malaysia (UTM)',
  'Universiti Utara Malaysia (UUM)',
  'Universiti Malaysia Sarawak (UNIMAS)',
  'Universiti Malaysia Sabah (UMS)',
  'Universiti Pendidikan Sultan Idris (UPSI)',
  'Universiti Teknologi MARA (UiTM)',
  'Universiti Islam Antarabangsa Malaysia (UIAM)',
  'Universiti Malaysia Terengganu (UMT)',
  'Universiti Sultan Zainal Abidin (UniSZA)',
  'Universiti Tun Hussein Onn Malaysia (UTHM)',
  'Universiti Teknikal Malaysia Melaka (UTeM)',
  'Universiti Malaysia Pahang Al-Sultan Abdullah (UMPSA)',
  'Universiti Malaysia Perlis (UniMAP)',
  'Universiti Malaysia Kelantan (UMK)',
  'Universiti Pertahanan Nasional Malaysia (UPNM)',

  // ── Private Universities ────────────────────────────────────────────────
  'Monash University Malaysia',
  'University of Nottingham Malaysia',
  'Heriot-Watt University Malaysia',
  'University of Southampton Malaysia',
  'Swinburne University of Technology Sarawak',
  'Curtin University Malaysia',
  'Xiamen University Malaysia',
  'Taylor\'s University',
  'Sunway University',
  'INTI International University',
  'Asia Pacific University of Technology & Innovation (APU)',
  'Multimedia University (MMU)',
  'UCSI University',
  'Universiti Tenaga Nasional (UNITEN)',
  'Universiti Tunku Abdul Rahman (UTAR)',
  'SEGi University',
  'Management and Science University (MSU)',
  'Limkokwing University of Creative Technology',
  'Universiti Kuala Lumpur (UniKL)',
  'HELP University',
  'Binary University of Management & Entrepreneurship',
  'Perdana University',
  'Quest International University',
  'Tunku Abdul Rahman University of Management and Technology (TAR UMT)',
  'Wawasan Open University',
  'Open University Malaysia (OUM)',
  'Al-Madinah International University (MEDIU)',
  'AIMST University',
  'Manipal International University',
  'Meritus University',
  'City University Malaysia',
  'Lincoln University College',
  'Nilai University',
  'MAHSA University',
  'International Medical University (IMU)',
  'Albukhary International University (AIU)',
  'Raffles University',
  'University of Cyberjaya',
  'Universiti Antarabangsa INTI (INTI-IU)',
  'DRB-HICOM University of Automotive Malaysia',
  'GlobalNxt University',
  'Universiti Selangor (UNISEL)',
  'Universiti Tun Abdul Razak (UNIRAZAK)',
  'Infrastructure University Kuala Lumpur (IUKL)',

  // ── University Colleges ─────────────────────────────────────────────────
  'Tunku Abdul Rahman University College (TAR UC)',
  'KDU University College',
  'INTI International College Subang',
  'Berjaya University College',
  'Reliance College',
  'Sunway College',
  'Taylor\'s College',

  // ── Polytechnics ────────────────────────────────────────────────────────
  'Politeknik Sultan Salahuddin Abdul Aziz Shah',
  'Politeknik Ungku Omar',
  'Politeknik Sultan Haji Ahmad Shah',
  'Politeknik Kota Bharu',
  'Politeknik Ibrahim Sultan',
  'Politeknik Port Dickson',
  'Politeknik Sultan Mizan Zainal Abidin',
  'Politeknik Merlimau',
  'Politeknik Kuching Sarawak',
  'Politeknik Kota Kinabalu',
  'Politeknik Seberang Perai',
  'Politeknik Sultan Idris Shah',
  'Politeknik Nilai',
  'Politeknik Muadzam Shah',
  'Politeknik Mukah',
  'Politeknik Metro Kuala Lumpur',
  'Politeknik Banting',
  'Politeknik Sandakan',
  'Politeknik Tuanku Sultanah Bahiyah',
  'Politeknik Jeli',
  'Politeknik Mersing',
  'Politeknik Hulu Terengganu',
  'Politeknik Balik Pulau',
  'Politeknik Tun Syed Nasir Syed Ismail',
  'Politeknik Metro Johor Bahru',
  'Politeknik Metro Kuantan',
  'Politeknik Metro Tasek Gelugor',
  'Politeknik Metro Betong Sarawak',
];
